name: employee-retention
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          echo "## Metrics" > report.md
          cat metrics.txt >> report.md

          echo "## Test set predictions confusion matrix" >> report.md
          cml-publish test_confusion_matrix.png --md >> report.md



          cml-send-comment report.md
